
#bundler_args: --without development
language: ruby
dist: bionic
rvm:
  - 2.7.1
#before_install:
#  - sudo add-apt-repository -y ppa:moti-p/cc
#  - sudo apt-get update
#  - sudo apt-get -y --reinstall install imagemagick
#  - printf "\n" | pecl install imagick-beta
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq tesseract-ocr tesseract-ocr-nld
  - sudo sed -i 's/name="disk" value="1GiB"/name="disk" value="8GiB"/' /etc/ImageMagick-6/policy.xml
  - identify -list resource | grep Disk | grep 8GiB # Check ImageMagick setting is actually working.
branches:
  only:
    - main 
notifications:
  email:
    - diapriid@gmail.com 
    - jrflood@illinois.edu
  on_failure: change
